# Generated by Django 3.1.5 on 2021-01-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentanalysis',
            name='reddit_created_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentenceanalysis',
            name='reddit_created_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionanalysis',
            name='reddit_created_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
