# Generated by Django 3.1.5 on 2021-01-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0003_tagmeanalysis_tagmesentenceanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentenceanalysis',
            name='is_analized',
            field=models.BooleanField(default=False),
        ),
    ]
