language: python
services:
    - docker
env:
    - DOCKER_COMPOSE_VERSION=1.27.4

before_install:
    - sudo apt-get update
    - ls -la
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

before_script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

script:
    - ls -la
    - docker-compose run web sh -c "python manage.py test"
    - docker-compose run web sh -c "coverage run --omit='*/.virtualenvs/*' manage.py test"
    - docker-compose run web sh -c "coverage report"

deploy:
    - provider: script
      script: 
        - docker-compose push
        - echo "PING"
        - zip -r latest *
        - mkdir -p dpl_cd_upload
        - mv latest.zip dpl_cd_upload/latest.zip
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_ACCESS_KEY
      local_dir: dpl_cd_upload
      skip_cleanup: true
      on: &2
        repo: gorkemyontem/SWE-573-2020
      bucket: sentiment-analyser-bucket
      region: eu-central-1
    - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_ACCESS_KEY
      bucket: sentiment-analyser-bucket
      key: latest.zip
      bundle_type: zip
      application: sentiment_analyser
      deployment_group: sentiment_analyser_deployment_group
      region: eu-central-1
      on: *2
    # - provider: heroku
    #   app: $HEROKU_APP
    #   api_key: $HEROKU_API_KEY
    #   on:
    #     all_branches: true

