version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        auth:
          username: gorkemyontem
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          - image: circleci/postgres:9.6.2 # an example of how to specify a service container
            auth:
              username: mydockerhub-user
              password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
            environment:
              POSTGRES_USER: root
              POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: echo "this is the build job"

workflows:
  main:
    jobs:
      - build-and-test

#Docker!12345