# Generated by Django 3.1.4 on 2021-01-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorRedditor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('redditor_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('created_utc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subreddit_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('display_name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('description_html', models.CharField(max_length=5000)),
                ('subscribers', models.IntegerField(default=0)),
                ('created_utc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('selftext', models.CharField(max_length=5000)),
                ('link_flair_template_id', models.CharField(max_length=500)),
                ('link_flair_text', models.CharField(max_length=500)),
                ('num_comments', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('upvote_ratio', models.FloatField(default=0.0)),
                ('created_utc', models.DateTimeField()),
                ('redditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.authorredditor')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_id', models.CharField(max_length=50, unique=True)),
                ('parent_id', models.CharField(max_length=50, unique=True)),
                ('body', models.CharField(max_length=5000)),
                ('body_html', models.CharField(max_length=5000)),
                ('distinguished', models.BooleanField(default=False)),
                ('is_submitter', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('created_utc', models.DateTimeField()),
                ('redditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.authorredditor')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.submission')),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.subreddit')),
            ],
        ),
    ]
