# Generated by Django 3.1.4 on 2021-01-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorRedditor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('redditor_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('created_utc', models.DateTimeField()),
                ('comment_karma', models.IntegerField(default=0)),
                ('link_karma', models.IntegerField(default=0)),
                ('total_karma', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subreddit_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('display_name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('description_html', models.CharField(max_length=5000)),
                ('subscribers', models.IntegerField(default=0)),
                ('lang', models.CharField(max_length=50)),
                ('over18', models.BooleanField(default=False)),
                ('subreddit_type', models.CharField(max_length=500)),
                ('quarantine', models.BooleanField(default=False)),
                ('restrict_commenting', models.BooleanField(default=False)),
                ('restrict_posting', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('created_utc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('selftext', models.CharField(max_length=5000)),
                ('link_flair_text', models.CharField(max_length=500, null=True)),
                ('num_comments', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('upvote_ratio', models.FloatField(default=0.0)),
                ('downs', models.IntegerField(default=0)),
                ('ups', models.IntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('over_18', models.BooleanField(default=False)),
                ('permalink', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('comment_sort', models.CharField(max_length=500)),
                ('content_categories', models.CharField(max_length=500)),
                ('discussion_type', models.CharField(max_length=500)),
                ('created_utc', models.DateTimeField()),
                ('redditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.authorredditor')),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.subreddit')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('permalink', models.CharField(max_length=50)),
                ('link_id', models.CharField(max_length=50)),
                ('parent_id', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=5000)),
                ('body_html', models.CharField(max_length=5000)),
                ('is_submitter', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('ups', models.IntegerField(default=0)),
                ('downs', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('controversiality', models.IntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('comment_type', models.CharField(max_length=500)),
                ('created_utc', models.DateTimeField()),
                ('redditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.authorredditor')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.submission')),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.subreddit')),
            ],
        ),
    ]
