# Generated by Django 3.1.4 on 2021-01-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
