# Generated by Django 3.1.4 on 2021-01-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='link_flair_template_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='link_flair_text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
