# Generated by Django 3.1.4 on 2021-01-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20210103_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='content_categories',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
