# Generated by Django 3.1.4 on 2021-01-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20210103_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='distinguished',
        ),
    ]
