# Generated by Django 3.1.4 on 2021-01-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20210103_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='comment_sort',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
