# Generated by Django 3.1.4 on 2021-01-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20210103_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='permalink',
            field=models.CharField(max_length=500),
        ),
    ]
