# Generated by Django 3.1.5 on 2021-01-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_auto_20210103_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_type',
        ),
        migrations.AddField(
            model_name='comments',
            name='is_analized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_analized',
            field=models.BooleanField(default=False),
        ),
    ]
